from __future__ import annotations

from app.raw_models import RawIoTData
from ml.control_action_classifier import MLControlActionClassifier


class ControlRecommendationEngine:
    """Selects one safe, condition-based EMS recommendation."""

    RECOMMENDATIONS = {
        "GRID_EXPORT": "Export surplus solar power to the grid.",
        "GRID_IMPORT": "Import power from the grid to meet the current load demand.",
        "CRITICAL_LOAD_PROTECTION": "Protect critical loads by reducing non-critical loads.",
        "OPTIMIZE_LOAD": "Optimize flexible loads to better match available solar generation.",
        "LOAD_SHIFT": "Shift flexible loads to the period of higher solar generation.",
        "LOAD_REDUCE": "Reduce non-critical energy consumption to lower grid dependency.",
        "MAINTAIN": "Maintain the current system operating state.",
    }

    MAINTENANCE_SCENARIOS = {
        "panel_soiling",
        "partial_shading",
        "inverter_inefficiency",
    }

    def __init__(self):
        self.classifier = MLControlActionClassifier()

    def _condition_action(
        self,
        data: RawIoTData,
        predicted_generation: float,
        scenario: str | None,
    ) -> str | None:

        # Maintenance/fault scenarios must not become EMS control actions.
        if scenario in self.MAINTENANCE_SCENARIOS:
            return None

        solar_power = data.solar.voltage * data.solar.current / 1000
        load_power = data.load.voltage * data.load.current / 1000

        battery_support = max(
            (data.load.current - data.solar.current)
            * data.battery.voltage
            / 1000,
            0.0,
        )

        available_generation = solar_power + battery_support

        grid_available = (
            data.grid.voltage > 0
            and data.grid.current >= 0
        )

        # Critical battery / supply condition has highest EMS priority.
        if data.battery.voltage < 11.8:
            return "CRITICAL_LOAD_PROTECTION"

        # Explicit high-energy-consumption scenario.
        if scenario == "high_energy_consumption":
            if (
                predicted_generation > solar_power * 1.25
                and solar_power > 0
            ):
                return "LOAD_SHIFT"

            return "LOAD_REDUCE"

        # Clear surplus solar.
        if grid_available and solar_power > load_power * 1.25:
            return "GRID_EXPORT"

        # Load exceeds current solar production.
        if load_power > solar_power * 1.15:

            # Grid can directly support the load.
            if grid_available:
                return "GRID_IMPORT"

            # If future solar is substantially better, shift flexible loads.
            if (
                predicted_generation > solar_power * 1.25
                and solar_power > 0
            ):
                return "LOAD_SHIFT"

            # Otherwise reduce non-critical loads.
            return "LOAD_REDUCE"

        # Moderate solar/load balance.
        if (
            solar_power > 0
            and load_power <= solar_power * 1.05
            and load_power > solar_power * 0.40
        ):
            return "OPTIMIZE_LOAD"

        return "MAINTAIN"

    def recommend(
        self,
        data: RawIoTData,
        predicted_generation: float,
        scenario: str | None,
        hardware_anomalies: list[dict] | None = None,
    ) -> dict:

        # Hardware safety anomalies always suppress EMS control.
        if hardware_anomalies:
            return {
                "control_action": None,
                "recommendation": None,
                "confidence": 0.0,
            }

        allowed_action = self._condition_action(
            data,
            predicted_generation,
            scenario,
        )

        # Maintenance/fault scenario: leave the maintenance
        # recommendation generated by the intelligence engine intact.
        if allowed_action is None:
            return {
                "control_action": None,
                "recommendation": None,
                "confidence": 0.0,
            }

        prediction = self.classifier.predict(
            data,
            predicted_generation,
        )

        # Deterministic condition logic is authoritative.
        if prediction["control_action"] == allowed_action:
            action = prediction["control_action"]
            confidence = prediction["confidence"]
        else:
            action = allowed_action
            confidence = 1.0

        return {
            "control_action": action,
            "recommendation": self.RECOMMENDATIONS[action],
            "confidence": confidence,
        }